version: "3.5"

services:
  mysqldb:
    image: mysql:5.7
    restart: always
    command: --explicit_defaults_for_timestamp
    environment:
      MYSQL_DATABASE: shortlinks
      MYSQL_USER: johndoe
      MYSQL_PASSWORD: testing
      MYSQL_ROOT_PASSWORD: testing
    ports:
      - "3306:3306"
    volumes:
      - ./docker/database/data:/var/lib/mysql
      - ./docker/database/init.sql:/data/application/init.sql

volumes:
  docker:


